[general]
import = ["~/.config/alacritty/rose-pine.toml"]

[window]
dynamic_title = true
padding = { x = 10, y = 5 }

[font]
normal = { family = "Maple Mono NF", style = "Regular" }
bold = { family = "Maple Mono NF", style = "Bold" }
italic = { family = "Maple Mono NF", style = "Italic" }
bold_italic = { family = "Maple Mono NF", style = "Bold Italic" }

[cursor]
style = { shape = "Beam", blinking = "Always" }
blink_interval = 400
unfocused_hollow = false
thickness = 0.35